# Generated by Django 5.1.3 on 2024-11-07 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sname', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('semail', models.EmailField(max_length=254)),
            ],
        ),
    ]
